### PR TITLE
increase BOOT_DISK_SIZE to 30GB

### PR DESCRIPTION
**Pull request by YZ775**
in order to follow changes in the PR below.
- https://github.com/cybozu-go/neco/pull/2688

### CODE REVIEW

**Review by zeroalphat — COMMENTED** [review]
Is it okay not to increase the disk size for the sonobuoy test?
https://github.com/cybozu-go/cke/blob/612456fa36986c4749c1b64de0797fc2515ee26c/bin/env-sonobuoy#L7

**Comment by YZ775** [comment]
@zeroalphat 
Thank you for checking.
It's no problem because sonobuoy does not use vmx-enabled image. 

https://github.com/cybozu-go/cke/blob/612456fa36986c4749c1b64de0797fc2515ee26c/bin/run-sonobuoy.sh#L22


Also, I manually triggered sonobuoy test and confirmed it have been passed in this branch.
https://github.com/cybozu-go/cke/actions/runs/11455822544

**Review by zeroalphat — APPROVED** [review]
LGTM

**Review by masa213f — APPROVED** [review]
LGTM

**Pull request merged**
